### ISSUE TITLE
pywin breaks unix support

### ISSUE THREAD

**Issue by RJ3** [kairosight/kairosight#2]
Unfortunately the change to pywin breaks support on non-Win platforms. Is there any way to revert this?

https://github.com/kairosight/kairosight/blob/26e975943648da84fde53dca2e47a74fb2118c28/requirements.txt#L38-L39

The commit was here:
https://github.com/kairosight/kairosight/commit/3d3bfe5860db0a9b3c8f3f4cc6e23f611f675dce#diff-b4ef698db8ca845e5845c4618278f29a

**Comment by damonmcc** [comment]
Since that's only needed to create a Windows executable from the source code, we can probably do without it.

Does it break non-Windows support if it isn't used by any UI or util files?

**Comment by RJ3** [comment]
Cool, thanks for your reply. It's probably fine then, I was having trouble loading the dependencies using 'pip3 install -r requirements.txt'
I'll try it again with those lines removed and circle back.
